language: java
jdk: oraclejdk8

sudo: false # faster builds

env:
  - TEST_DIR=AtlantisJavaEE-ejb

cache:
 directories:
 - $HOME/.m2
 - $HOME/.m2/repository

script:
- cd $TEST_DIR && mvn test -X

notifications:
 email: false
 slack: atlantisprojectgroup:TWfvPT2fjFOVmh97nehKRzqZ

